#! /bin/sh

set -x

if [ -z "$OUTPUT_DIRECTORY" ]; then
  OUTPUT_DIRECTORY=$(pwd)
fi

if ! which dch >/dev/null; then
  echo >&2 "please install devscripts"
  exit 1
fi

if ! which debootstrap >/dev/null; then
  echo >&2 "please install debootstrap"
  exit 1
fi

germinate-update-metapackage
